#* Directories
model_name: onnx
mode: test_onnx        # options: 'train', 'test', 'concat_train', 'subset_test'

data_dir: dataset/SPA

data_concat_train_dir: null

test_subset_dir: null

#* Train
batch_size: 2
learning_rate: 0.0001
weight_decay: 0
num_epoch: 300
print_freq: 100
num_worker: 1
save_freq: 1
valid_freq: 1
resume: null
gamma: 0.5
patience: 50  # Increased patience for early stopping
num_res: 4  # Number of residual blocks in the model

#* Test
test_model: /home/giovannidistasio/vista/models/ConvIR/Image_deraining/convIR_int8_excluded_rain.onnx
save_image: false
number_subsets: 10  # number of subsets for random sampling of the test set
subset_ratio: 0.2  # ratio of images to sample for each subset

#* Logging
model_save_dir: onnx/ConvIR/train/
result_dir: onnx/test 

notes: |
  # onnx of the chosen model