#* Directories
model_name: small_version_RR_H_TEST_ON_SPA
mode: test     # options: 'train', 'test', 'concat_train', 'subset_test'

data_dir:  dataset/SPA

data_concat_train_dir: null

test_subset_dir: null

#* Train
batch_size: 2
learning_rate: 0.0001
weight_decay: 0
num_epoch: 300
print_freq: 100
num_worker: 1
save_freq: 1
valid_freq: 1
resume: null
gamma: 0.5
patience: 50  # Increased patience for early stopping
num_res: 4  # Number of residual blocks in the model

#* Test
test_model: RESULTS/small_version_RR_H/ConvIR/train/Best.pkl
save_image: true
number_subsets: 10  # number of subsets for random sampling of the test set
subset_ratio: 0.6  # ratio of images to sample for each subset

#* Logging
model_save_dir: results2/ConvIR/train/
result_dir: results2/small_version_RR_H_TEST_ON_SPA/test 

notes: |
  small version trained on RealRain-1k-H