#* Directories
model_name: small_version_LHP_RR_LW
mode: subset_test     # options: 'train', 'test', 'concat_train', 'subset_test'

data_dir: null

data_concat_train_dir:
  - dataset/LHP
  - dataset/RealRain-1k/RealRain-1k-L
  - dataset/RealRain-1k/RealRain-1k-H

test_subset_dir:
  - dataset/LHP
  - dataset/RealRain-1k/RealRain-1k-L
  - dataset/RealRain-1k/RealRain-1k-H

#* Train
batch_size: 2
learning_rate: 0.0001
weight_decay: 0
num_epoch: 300
print_freq: 100
num_worker: 1
save_freq: 1
valid_freq: 1
resume: null
gamma: 0.5
patience: 50  # Increased patience for early stopping
num_res: 4  # Number of residual blocks in the model

#* Test
test_model: small_version_LHP_RR_LW/ConvIR/train/Best.pkl
save_image: true
number_subsets: 10  # number of subsets for random sampling of the test set
subset_ratio: 0.3  # ratio of images to sample for each subset

#* Logging
model_save_dir: small_version_LHP_RR_LW/ConvIR/train/
result_dir: small_version_LHP_RR_LW/test 

notes: |
  small model trained on LHP and both L and H of RealRain-1k