#* Directories
model_name: onnx_quantized # experiment name
mode: subset_test_onnx      # options: 'train', 'test', 'subset_test', 'concat_train'
type: small       # options: 'small', 'base', 'large'

data_dir: null  # folder for normal train, val and test 

data_curriculum_learning_dir: null # list of folders for Curriculum Learning

data_concat_train_dir: null

test_subset_dir:  # list of folders for testing on multiple datasets and tested with random sampling
  - dataset/benchmark_splitted/Dense_Haze
  - dataset/benchmark_splitted/I-HAZE
  - dataset/benchmark_splitted/O-HAZE
  - dataset/benchmark_splitted/NH-HAZE
  - dataset/custom_dataset_splitted


#* train
batch_size: 2
learning_rate: 0.0001
weight_decay: 0
num_epoch: 300
print_freq: 100
num_worker: 4
save_freq: 1
valid_freq: 1
resume: null  # path to model to resume training
phase: easy  # options for Curriculum Learning: 'easy', 'medium', 'hard', 'extreme'. Use easy for normal training without Curriculum Learning
patience: 50  # for early stopping

#* test
test_model: convIR_int8_excluded_haze.onnx # path to model to be tested
save_image: true  # options: true, false
number_subsets: 10  # number of subsets for random sampling of the test set
subset_ratio: 0.6  # ratio of images to sample for each subset

#* logging
model_save_dir: onnx_quantized/ConvIR/OTS/  # directory to save models
result_dir: onnx_quantized/test  # directory to save test results



notes: |
  Onnx quantized of the chosen model trained on multiple datasets (Dense-Haze, I-HAZE, O-HAZE, NH-HAZE and custom synthetic dataset)