#* Directories
model_name: onnx # experiment name
mode: subset_test_onnx      # options: 'train', 'test', 'subset_test', 'concat_train'
data_dir: null      # options: 'small', 'base', 'large'

data_concat_train_dir: null

test_subset_dir:
  # - dataset/realsnow_video
  # - dataset/RealSnow10k_pairs
  # - dataset/Realsnow85
  - dataset/pipe


#* train
batch_size: 2
learning_rate: 0.0001
weight_decay: 0
num_epoch: 300
print_freq: 100
num_worker: 4
save_freq: 1
valid_freq: 1
resume: null  # path to model to resume training
phase: easy  # options for Curriculum Learning: 'easy', 'medium', 'hard', 'extreme'. Use easy for normal training without Curriculum Learning
patience: 50  # for early stopping
version: small

#* test
test_model: convIR_int8_excluded_snow.onnx # path to model to be tested
save_image: true  # options: true, false
number_subsets: 1 # number of subsets for random sampling of the test set
subset_ratio: 1 # ratio of images to sample for each subset

#* logging
model_save_dir: onnx/ConvIR/OTS/  # directory to save models
result_dir: onnx/test  # directory to save test results



notes: |
  Onnx of the chosen model trained on multiple datasets (Dense-Haze, I-HAZE, O-HAZE, NH-HAZE and custom synthetic dataset)