#* Directories
model_name: small_version_RV_RS85_RS10K_resume
mode: subset_test  # options: 'train', 'test', 'concat_train', 'subset_test'
data_dir: null

data_concat_train_dir:
  - dataset/realsnow_video
  - dataset/RealSnow10k_pairs
  - dataset/Realsnow85

test_subset_dir:
  - dataset/realsnow_video
  - dataset/RealSnow10k_pairs
  - dataset/Realsnow85


#* Train
batch_size: 2
learning_rate: 0.0002
weight_decay: 0
num_epoch: 400
print_freq: 100
num_worker: 4
save_freq: 1
valid_freq: 1
resume: ckpt/snow100k-small.pkl
patience: 65  # Increased patience for early stopping
version: small

#* Test
test_model: small_version_RV_RS85_RS10K_resume/ConvIR/train/Best.pkl
save_image: true
number_subsets: 10  # number of subsets for random sampling of the test set
subset_ratio: 0.1  # ratio of images to sample for each subset

#* Logging
model_save_dir: small_version_RV_RS85_RS10K_resume/ConvIR/train/
result_dir: small_version_RV_RS85_RS10K_resume/test 

notes: |
  small version of the pretrained model trained on realsnow_video, RealSnow10k_pairs and Realsnow85